### ISSUE TITLE
Library building and refurbishment data

### ISSUE THREAD

**Issue by sallybaker** [hughrun/public_library_map#104]
More of an idea than an issue, but it might be useful to know how old the library building is and/or how long since the last refurbishment. I imagine being able to visualise library infrastructure across the country could be useful in higher level planning. 

And while, we're on the subject, the age of the library service itself could be interesting to know as well.

**Comment by hughrun** [comment]
Age of building stock could be really interesting. I was thinking about age of library service last week: it _could_ be interesting, but a complication that makes it possibly less useful is where Councils have merged, or they've formed a joint library corp. e.g. some library services in Sydney would be much "younger" than their own libraries. There's some ways around that but we would run into a few definitional arguments for sure!

**Comment by sallybaker** [comment]
All good points! Maybe if we consider the library as a separate entity from the council currently running it. And then consider official/unofficial library opening date as 'Established'. Any change of building premises, major renovation or upgrade could be 'Last upgrade' or something to that effect.  

Not sure where we'd source the age of building stock from??? Might have to go direct to the source...
