### ISSUE TITLE
hyperlinked software vendor data

### ISSUE THREAD

**Issue by musiczetetic** [hughrun/public_library_map#109]
If I could click on a software/vendor and see a list of all other libraries using that it would be very useful. 

For example I am interested in who is using Koha but because there are so few it is hard to gauge the actual use of it.

**Comment by hughrun** [comment]
Hmm, should be possible, there are a few options to do this. In the meantime I can tell you there are three public libraries using Koha - Derby-West Kimberley (WA) Northam (WA), and Brimbank (Vic).

**Comment by musiczetetic** [comment]
Thanks Hugh. I had found Derby-West from the Koha user site, Northam on your map, but had not found Brimbank anywhere. Cheers.

**Comment by hughrun** [comment]
@musiczetetic I did the rollout when I was at Brimbank :-) Support from Catalyst IT.

**Comment by musiczetetic** [comment]
Good to know. I have looked at Catalyst and think I might have found one other support option in Australia. I might come to you with some questions when the time comes, I am hoping my library will seriously consider it as an option.

**Comment by hughrun** [comment]
Resolved with #176
