### ISSUE TITLE
add SA fines data

### ISSUE THREAD

**Issue by hughrun** [hughrun/public_library_map#124]

**Comment by mohitbalwani** [comment]
Hey I would like to work on this issue.

**Comment by hughrun** [comment]
Thanks @mohitbalwani. This issue is really about data collection rather than coding, so if you change your mind that's ok 😆

We need to find out which South Australian (SA) libraries charge fines, and add that data to `library_services_information.csv`. I have already checked most of the library websites and they do not seem to provide this information - this is why the CSV file has question marks rather than blanks in many places.
