### ISSUE TITLE
Corangamite Regional Library Corporation boundary + membership changes

### ISSUE THREAD

**Issue by lissertations** [hughrun/public_library_map#129]
Geelong Regional Library Corporation now includes libraries in Colac and Apollo Bay plus mobile library services in Colac Otway Shire, after that council voted to leave Corangamite Regional Library Corporation and join GRLC: https://www.grlc.vic.gov.au/colacotwayshire

Warrnambool Library is now an independent entity run by that council in conjunction with the local TAFE, while CRLC manages the remaining libraries in Corangamite and Moyne shires and will be wound up at the end of the 2021-22 financial year: https://www.corangamite.vic.gov.au/Council/Have-Your-Say/Library-survey

The relevant boundaries will need to be redrawn. Warrnambool Library runs on Spydus and has a 3 week borrowing period. Their website makes no mention of fines.

**Comment by hughrun** [comment]
Oh boy, this is confusing.

**Comment by lissertations** [comment]
Essentially:
- Colac Otway shire added to Geelong Regional boundaries
- Warrnambool council now doing its own thing
- Corangamite + Moyne shires still together (but possibly not for much longer who knows)
