### ISSUE TITLE
include license and citation guides in "contributing"

### ISSUE THREAD

**Issue by hughrun** [hughrun/public_library_map#15]
Also would be good to have a PR template with a checklist for licensing and permissions. e.g.

- [ ] I agree my contribution is licensed CC-BY (for /websiite/data) or GPL-3.0 (everything else)
- [ ] Any data I have added from another source has been cited appropriately in `sources.md` and `/sources/index.html`.

**Comment by nemobis** [comment]
Thanks for adding a license! Why CC-BY-SA though? It doesn't disclaim [database rights](https://en.wikipedia.org/wiki/Database_right), which is not a problem in Australia (until the EU decides to force them down your throat with some trade treaty) but can be a problem for international users. [CC-0](https://creativecommons.org/publicdomain/zero/1.0/) is an alternative.

**Comment by hughrun** [comment]
CC-0 is problematic:

>  You can copy, modify, distribute and perform the work, even for commercial purposes, all without asking permission. 

I'm not interested in allowing corporations to enclose this data. This is not hypothetical, public domain library and research data is routinely claimed by litigious corporations with deep pockets.

Unless international contributors are worried I will claim "database rights" (which I wont', can't since I'm in Australia, and this data all relates to Australia anyway), I'm not really sure what the problem is?

**Comment by nemobis** [comment]
Il 29/10/22 11:17, Hugh Rundle ha scritto:
> I'm not really sure what the problem is?

I'm thinking whether this data would be useful for Wikidata, but if it's 
not CC-0 I may not even start looking at it because it would take more 
effort to assess its copyright status.
