### ISSUE TITLE
how to deal with libraries with membership fees?

### ISSUE THREAD

**Issue by hughrun** [hughrun/public_library_map#22]
Norfolk Island library has an annual fee. So do (most? all?) Mechanics Institutes, and also there are some subscription libraries like the Atheneum in Melbourne which is not on the map. Are these their own category?

**Comment by lissertations** [comment]
The Melbourne Athenaeum is privately run while the Norfolk Island library is run by the local council (I suspect the membership fees are a hangover from self-government days). I would be inclined to add another layer for membership fees, as these are distinct from library fines, and can apply to multiple types of public library.

As for whether the Athenaeum belongs on the map... I also noticed its omission, and I suppose it started life as a mechanics' institute, so it could be placed in that category. But I'm not sure about other subscription libraries (are there any?).

**Comment by hughrun** [comment]
Norfolk Island will be the only "public library service" that charges fees, so it's a bit anomalous. I'm wondering if it makes more sense to simply replace the Mechanics Institutes category with a subscription library category. There's the Sydney Mechanics School of Arts and I think one in Adelaide as well.

**Comment by lissertations** [comment]
Perhaps renaming that category to 'Mechanics Institutes and Subscription Libraries' would work? I don't have any other ideas for the fees info.

**Comment by hughrun** [comment]
Having considered this a little more, Schools of Arts & Mechanics Institutes should be one category, referred to as Mechanics Institutes as this is a more general term. Obviously some data is missing. Norfolk Island is a special case.
