### ISSUE TITLE
add website address to library services pop-up on selecting area

### ISSUE THREAD

**Issue by hughrun** [hughrun/public_library_map#26]
This requires updating `zoomToFeature`. 

For it to have much effect we also need to add URLs to to `library_services_information.csv` but that is a separate ticket.

**Comment by hughrun** [comment]
This requires updating `zoomToFeature` and adding URLs to to `library_services_information.csv`

**Comment by sallybaker** [comment]
New PR should display link to website, or 'Unknown' if the website hasn't been added yet 👍
