### ISSUE TITLE
LMS layer: 'OCLC Worldcat' and 'OCLC Worldshare' are the same thing

### ISSUE THREAD

**Issue by lissertations** [hughrun/public_library_map#31]
Formally titled ['OCLC WorldShare Management Services'](https://www.oclc.org/en/worldshare-management-services.html)

**Comment by lissertations** [comment]
I spot-checked a few and they all look the same.

**Comment by hughrun** [comment]
Sorry, just realised you already have a PR for this.

**Comment by lissertations** [comment]
Excluding NT libraries, which I know for a fact all use WMS in a consortial arrangement, I went back and checked all libraries previously marked 'OCLC Worldcat'. Three were confirmed to be WMS libraries as per their OPACs and Marshall Breeding's library technology guide, while the fourth is now a Libero library as of 2019, so that has been updated in the csv as well.

**Comment by hughrun** [comment]
Fixes in #33
