### ISSUE TITLE
Add library service URLs to library_services_information.csv

### ISSUE THREAD

**Issue by hughrun** [hughrun/public_library_map#39]
There's only about 400 on the list so this should be easy 🤣 

This can be done incrementally. Please don't use auto-closing language like `fixes #39` in commits or PRs for this task.

**Comment by sallybaker** [comment]
Best assign me to this issue as well @hughrun. I'll work on adding the QLD ones to start with...

**Comment by madradish** [comment]
I can add WA library URLs once I’ve updated the address data.

**Comment by sallybaker** [comment]
Qld URLs have been added! 😃

**Comment by hughrun** [comment]
WA, NT and NSW (thanks @madradish ) and Qld (thanks @sallybaker ) are done. Closing this and opening separate ones for SA and Vic.
