### ISSUE TITLE
Rockhampton Regional Library Administration and History Centre

### ISSUE THREAD

**Issue by hughrun** [hughrun/public_library_map#43]
Is this a real library? `public_library_locations.csv` may need to be updated.

**Comment by lissertations** [comment]
The coordinates for 'Rockhampton Regional Library Administration and History Centre' on line 1170 of that csv resolve to a spot just over the road from the Southside Library on Bolsover St, Rockhampton, which is line 435. I think library admin are probably located within that building, so not a 'real library' for mapping purposes.
