### ISSUE TITLE
Should Northern Territory "Knowledge Centres" be classified as Indigenous Knowledge Centres?

### ISSUE THREAD

**Issue by hughrun** [hughrun/public_library_map#90]
Queensland State Library clearly distinguishes IKCs, but the Northern Territory Library is a bit vaguer.

**Comment by lissertations** [comment]
I'm not sure NTL / LANT ever formally distinguished urban and remote libraries in this way, even when the 'Library and Knowledge Centre' concept was in wide use (see this [2005 eval report](https://web.archive.org/web/20110805202521/http://www.ntl.nt.gov.au/__data/assets/pdf_file/0018/4680/nakata_finalreport.pdf)). I would therefore be reluctant to impose such a reclassification on them. It does, however, expose some philosophical differences between LANT and SLQ on the cultural inclusiveness of the term 'library'.

An interesting thought experiment would be to reclassify _all_ libraries in the NT as IKCs.
