### ISSUE TITLE
Libraries ACT data no longer appears on the map

### ISSUE THREAD

**Issue by lissertations** [hughrun/public_library_map#97]
![image](https://user-images.githubusercontent.com/22556371/106430356-caddd980-64bf-11eb-812d-949e6dea1cd7.png)

All relevant data remains in `library_services_information.csv` (and is the first item in that list), but only the name and the boundary data appears in `boundaries.topo.json`.

**Comment by hughrun** [comment]
Thanks. This is a regression from 100f31474386a0060ef29f40fd798ab04b0e89e6 because the GeoJSON file had "Act" instead of "ACT". I must have update it in the TopoJSON and not the GeoJSON, which is a lesson for us all: don't manually update the TopoJSON!
